name: PR - Terraform Doc
on:
  workflow_dispatch:

  pull_request:
  

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
       ref: ${{ github.event.pull_request.head.ref }}

    - name: Render TF_docs - palo-deploy
      uses: terraform-docs/gh-actions@v1.0.0
      with:
        working-dir: ./palo-deploy
        output-file: README.md
        output-method: inject
        git-push: "true"

    # - name: Render TF_docs - 02-AzureAd
    #   uses: terraform-docs/gh-actions@v1.0.0
    #   with:
    #     working-dir: ./02-AzureAd
    #     output-file: README.md
    #     output-method: inject
    #     git-push: "true"
